spring:
  config:
    activate:
      on-profile: local

external:
  naver:
#    url: https://openapi.naver.com
    url: ${NAVER_API_URL:http://localhost:9090}
    headers:
#      client-id: ${NAVER_API_CLIENT_ID}
#      client-secret: ${NAVER_API_CLIENT_SECRET}
      client-id: ${NAVER_API_CLIENT_ID:mock-client-id}
      client-secret: ${NAVER_API_CLIENT_SECRET:mock-client-secret}
